apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore
  description: The Petstore API
  annotations:
    github.com/dumdumorg: dir:docs
spec:
  type: openapi
  lifecycle: production
  owner: user:guest

