apiVersion: app-techdocs.com/v1.0.0
kind: Component
metadata:
  name: example
  description: example.com
  annotations:
    github.com/dumdumorg: dir:.
spec:
  type: website
  lifecycle: production
  owner: user:guest


