apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore
  description: The Petstore API
  annotations:
    backstage.io/techdocs-ref: dir:./docs
spec:
  type: openapi
  lifecycle: production
  owner: user:guest

